#ifndef REGISTER_H 
#define REGISTER_H

//Include 
#include <stdint.h>

//Registers 
#define UDR0    (*(volatile uint8_t *)(0xC6))
#define UBRR0H  (*(volatile uint8_t *)(0xC5))
#define UBRR0L  (*(volatile uint8_t *)(0xC4))
#define UCSR0C  (*(volatile uint8_t *)(0xC2))
#define UCSR0B  (*(volatile uint8_t *)(0xC1))
#define UCSR0A  (*(volatile uint8_t *)(0xC0))
#define TWAMR   (*(volatile uint8_t *)(0xBD))
#define TWCR    (*(volatile uint8_t *)(0xBC))
#define TWDR    (*(volatile uint8_t *)(0xBB))
#define TWAR    (*(volatile uint8_t *)(0xBA))
#define TWSR    (*(volatile uint8_t *)(0xB9))
#define TWBR    (*(volatile uint8_t *)(0xB8))
#define ASSR    (*(volatile uint8_t *)(0xB6))
#define OCR2B   (*(volatile uint8_t *)(0xB4))
#define OCR2A   (*(volatile uint8_t *)(0xB3))
#define TCNT2   (*(volatile uint8_t *)(0xB2))
#define TCCR2B  (*(volatile uint8_t *)(0xB1))
#define TCCR2A  (*(volatile uint8_t *)(0xB0))
#define OCR1BH  (*(volatile uint8_t *)(0x8B))
#define OCR1BL  (*(volatile uint8_t *)(0x8A))
#define OCR1AH  (*(volatile uint8_t *)(0x89))
#define OCR1AL  (*(volatile uint8_t *)(0x88))
#define ICR1H   (*(volatile uint8_t *)(0x87))
#define ICR1L   (*(volatile uint8_t *)(0x86))
#define TCNT1H  (*(volatile uint8_t *)(0x85))
#define TCNT1L  (*(volatile uint8_t *)(0x84))
#define TCCR1C  (*(volatile uint8_t *)(0x82))
#define TCCR1B  (*(volatile uint8_t *)(0x81))
#define TCCR1A  (*(volatile uint8_t *)(0x80))
#define DIDR1   (*(volatile uint8_t *)(0x7F))
#define DIDR0   (*(volatile uint8_t *)(0x7E))
#define ADMUX   (*(volatile uint8_t *)(0x7C))
#define ADCSRB  (*(volatile uint8_t *)(0x7B))
#define ADCSRA  (*(volatile uint8_t *)(0x7A))
#define ADCH    (*(volatile uint8_t *)(0x79))
#define ADCL    (*(volatile uint8_t *)(0x78))
#define TIMSK2  (*(volatile uint8_t *)(0x70))
#define TIMSK1  (*(volatile uint8_t *)(0x6F))
#define TIMSK0  (*(volatile uint8_t *)(0x6E))
#define PCMSK2  (*(volatile uint8_t *)(0x6D))
#define PCMSK1  (*(volatile uint8_t *)(0x6C))
#define PCMSK0  (*(volatile uint8_t *)(0x6B))
#define EICRA   (*(volatile uint8_t *)(0x69))
#define PCICR   (*(volatile uint8_t *)(0x68))
#define OSCCAL  (*(volatile uint8_t *)(0x66))
#define PRR     (*(volatile uint8_t *)(0x64))
#define CLKPR   (*(volatile uint8_t *)(0x61))
#define WDTCSR  (*(volatile uint8_t *)(0x60))
#define SREG    (*(volatile uint8_t *)(0x5F))
//Two Memory Address
#define SPH     (*(volatile uint8_t *) (0x5E))
#define SPL     (*(volatile uint8_t *) (0x5D))
#define SPMCSR  (*(volatile uint8_t *) (0x57))
#define MCUCR   (*(volatile uint8_t *) (0x55))
#define MCUSR   (*(volatile uint8_t *) (0x54))
#define SMCR    (*(volatile uint8_t *) (0x53))
#define ACSR    (*(volatile uint8_t *) (0x50))
#define SPSR    (*(volatile uint8_t *) (0x4D))
#define SPCR    (*(volatile uint8_t *) (0x4C))
#define SPDR    (*(volatile uint8_t *)(0x4E)) // SPI Data Register (The mailbox)
#define GPIOR2  (*(volatile uint8_t *) (0x4B))
#define GPIOR1  (*(volatile uint8_t *) (0x4A))
#define OCR0B   (*(volatile uint8_t *) (0x48))
#define OCR0A   (*(volatile uint8_t *) (0x47))
#define TCNT0   (*(volatile uint8_t *) (0x46))
#define TCCR0B  (*(volatile uint8_t *) (0x45))
#define TCCR0A  (*(volatile uint8_t *) (0x44))
#define GTCCR   (*(volatile uint8_t *) (0x43))
#define EEARH   (*(volatile uint8_t *) (0x42))
#define EEARL   (*(volatile uint8_t *) (0x41))
#define EEDR    (*(volatile uint8_t *) (0x40))
#define EECR    (*(volatile uint8_t *) (0x3F))
#define GPIOR0  (*(volatile uint8_t *) (0x3E))
#define EIMSK   (*(volatile uint8_t *) (0x3D))
#define EIFR    (*(volatile uint8_t *) (0x3C))
#define PCIFR   (*(volatile uint8_t *) (0x3B))
#define TIFR2   (*(volatile uint8_t *) (0x37))
#define TIFR1   (*(volatile uint8_t *) (0x36))
#define TIFR0   (*(volatile uint8_t *) (0x35))
#define PORTD   (*(volatile uint8_t *) (0x2B))
#define DDRD    (*(volatile uint8_t *) (0x2A))
#define PIND    (*(volatile uint8_t *) (0x29))
#define PORTC   (*(volatile uint8_t *) (0x28))
#define DDRC    (*(volatile uint8_t *) (0x27))
#define PINC    (*(volatile uint8_t *) (0x26))
#define PORTB   (*(volatile uint8_t *) (0x25))
#define DDRB    (*(volatile uint8_t *) (0x24))
#define PINB    (*(volatile uint8_t *) (0x23))

//User Defined
#define ADC_RES (*(volatile uint16_t *)(0x78))

#endif